

######################### forDeal ##########################
[forDeal]

#品类ID，下载这个品类下的图片
catId = 70000294
# 按照 like 数排名
limit = [0,40]

#------------------#
# 根据单个图片id 下载
detailIds = []

    [forDeal.puzzle] #拼图相关配置
    style  = 3  # 拼接样式 1.
    color = "black"  #字体颜色
    fontsize = 25  #字体大小
    count  = 4    #几张图片拼一起
    logo = "logo.png" #左上角logo
######################### forDeal ############################

